[package]
name = "rsnap-cart"
version = "0.0.1"
authors = ["Ross Crawford-d'Heureuse <r.crawford@douglas.de>"]

[dependencies]
sapper = "0.1"
env_logger = "0.4.3"
log = "0.3.8"

serde_json = "1.0.6"

bson = "0.10.0"
mongodb = "0.3.7"

config = "0.6"
reqwest = "0.8.1"
